Models/CodeFirst/Item.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace cwagnerShoppingApp.Models.CodeFirst
{
    public class Item
    {
        public int Id { get; set; }
        [Display(Name = "Creation Date")]
        public DateTime CreationDate { get; set; }
        [Display(Name = "Updated Date")]
        public DateTime? UpdatedDate { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        [Display(Name = "Image")]
        public string MediaURL { get; set; }
        [AllowHtml]
        public string Description { get; set; }
    }
}

Controllers/CartItemsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using cwagnerShoppingApp.Models;
using cwagnerShoppingApp.Models.CodeFirst;
using Microsoft.AspNet.Identity;

namespace cwagnerShoppingApp.Controllers
{
    public class CartItemsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public ActionResult CartMenu()
        {
            if (User.Identity.IsAuthenticated)
            {
                var userId = User.Identity.GetUserId();
                var user = db.Users.Find(userId);
                var itemCount = user.CartItems.Sum(y => y.Count);
                ViewBag.CartHasItems = true;
                return PartialView("_CartMenu", itemCount);
            }
            return PartialView("_CartMenu", null);
        }

        // GET: CartItems
        [Authorize]
        public ActionResult Index()
        {
            var id = User.Identity.GetUserId();
            var user = db.Users.Find(id);
            return View(user.CartItems.ToList());
        }

        // GET: CartItems/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CartItem cartItem = db.CartItems.Find(id);
            if (cartItem == null)
            {
                return HttpNotFound();
            }
            return View(cartItem);
        }

        // GET: CartItems/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CartItems/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(int? itemId)
        {
            var user = db.Users.Find(User.Identity.GetUserId());

            if (itemId != null || user != null)
            {                
                if (db.CartItems.Where(i => i.CustomerId == user.Id).Any(i => i.ItemId == itemId.Value))
                {
                    var existingCartItem = db.CartItems.Where(i => i.CustomerId == user.Id).FirstOrDefault(i => i.ItemId == itemId.Value);
                    existingCartItem.Count++;
                }
                else
                {
                    CartItem cartItem = new CartItem();
                    cartItem.ItemId = (int)itemId;
                    cartItem.CustomerId = user.Id;
                    cartItem.Count = 1;
                    cartItem.CreationDate = DateTime.Now;
                    db.CartItems.Add(cartItem);
                }
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View();
        }

        // GET: CartItems/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CartItem cartItem = db.CartItems.Find(id);
            if (cartItem == null)
            {
                return HttpNotFound();
            }
            return View(cartItem);
        }

        // POST: CartItems/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,ItemId,Count,CreationDate,CustomerId")] CartItem cartItem)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cartItem).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(cartItem);
        }

        // GET: CartItems/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CartItem cartItem = db.CartItems.Find(id);
            if (cartItem == null)
            {
                return HttpNotFound();
            }
            return View(cartItem);
        }

        // POST: CartItems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CartItem cartItem = db.CartItems.Find(id);
            db.CartItems.Remove(cartItem);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace cwagnerShoppingApp.Controllers
{
    public class ContactController : Controller
    {
        // GET: Contact
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Employment()
        {
            return View();
        }

        public ActionResult Subscribe()
        {
            return View();
        }
    }
}

Controllers/ItemsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using cwagnerShoppingApp.Models;
using cwagnerShoppingApp.Models.CodeFirst;

namespace cwagnerShoppingApp.Controllers
{
    public class ItemsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Items
        public ActionResult Index()
        {
            return View(db.Items.ToList());
        }

        // GET: Items/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = db.Items.Find(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);
        }

        // GET: Items/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Items/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Price,Description")] Item item, HttpPostedFileBase image)
        {
            if (image != null && image.ContentLength > 0)
            {
                var ext = Path.GetExtension(image.FileName).ToLower();
                if (ext != ".png" && ext != ".jpg" && ext != ".jpeg" && ext != ".gif" && ext != ".bmp")
                {
                    ModelState.AddModelError("image", "Invalid Format.");
                }
            }
            if (ModelState.IsValid)
            {
                var filePath = "/assets/Images/";
                var absPath = Server.MapPath("~" + filePath);
                item.MediaURL = filePath + image.FileName;
                image.SaveAs(Path.Combine(absPath, image.FileName));
                item.CreationDate = System.DateTime.Now;
                db.Items.Add(item);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(item);
        }

        // GET: Items/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = db.Items.Find(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);
        }

        // POST: Items/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,CreationDate,UpdatedDate,Name,Price,MediaURL,Description")] Item item, string mediaURL, HttpPostedFileBase image)
        {
            if (image != null && image.ContentLength > 0)
            {
                var ext = Path.GetExtension(image.FileName).ToLower();
                if (ext != ".png" && ext != ".jpg" && ext != ".jpeg" && ext != ".gif" && ext != ".bmp")
                {
                    ModelState.AddModelError("image", "Invalid Format.");
                }
            }
            if (ModelState.IsValid)
            {
                if (image != null)
                {
                    var filePath = "/assets/Images/";
                    var absPath = Server.MapPath("~" + filePath);
                    item.MediaURL = filePath + image.FileName;
                    image.SaveAs(Path.Combine(absPath, image.FileName));
                }
                else
                {
                    item.MediaURL = mediaURL;
                }

                item.UpdatedDate = System.DateTime.Now;
                db.Entry(item).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(item);
        }

        // GET: Items/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = db.Items.Find(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);
        }

        // POST: Items/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Item item = db.Items.Find(id);
            var absPath = Server.MapPath("~" + item.MediaURL);
            System.IO.File.Delete(absPath);
            db.Items.Remove(item);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult DaySeries()
        {
            return View();
        }

        public ActionResult NightSeries()
        {
            return View();
        }

        public ActionResult Collection18()
        {
            return View();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Items/Collection18.cshtml
@{
    ViewBag.Title = "Collection18";
}

<div class="InnerContent">
    <h2>2018 Collection</h2>

    <div>
        <h3><b>COMING SOON!!!</b></h3>
        <h4>Please check back soon or subscribe for updates!</h4>
        <p>
            Browse watches from our newest collections!  The new year is just a few short months away.  Make a resolution to enjoy the present
            time and look forward to what the future holds with our 2018 collection!
        </p>
    </div>
</div>

Views/Items/Create.cshtml
@model cwagnerShoppingApp.Models.CodeFirst.Item

@{
    ViewBag.Title = "Create";
}
<div class="InnerContent">
    <h2>Create Item</h2>


    @using (Html.BeginForm("Create", "Items", FormMethod.Post, new { enctype = "Multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @*<div class="form-group">
                @Html.LabelFor(model => model.CreationDate, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CreationDate, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CreationDate, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.UpdatedDate, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.UpdatedDate, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.UpdatedDate, "", new { @class = "text-danger" })
                </div>
            </div>*@

            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class = "control-label col-md-2">Upload Image</label>
                <div class="col-md-10">
                    <input name="image" type="file" class="form-control" />
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <textarea id="editor" class="form-control" name="Description" rows="5"></textarea>
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/tinymce/tinymce.min.js"></script>
    <script src="~/Scripts/tinymce/jquery.tinymce.min.js"></script>
    <script type="text/javascript"> 
        $(function () {
            tinymce.init({
                selector: '#editor'
            });
        }); </script>
}

Views/Items/DaySeries.cshtml
@{
    ViewBag.Title = "DaySeries";
}

<div class="InnerContent">
    <h2>Day Series</h2>

    <div>
        <h3><b>COMING SOON!!!</b></h3>
        <h4>Please check back soon or subscribe for updates!</h4>
        <p>
            Browse watches from our newest collections!  Our Day Series watches are some of the most cutting-edge and stylish watches out there!
            You're going to want to wear these watches longer than just during the day!
        </p>
    </div>
</div>

Views/Items/Delete.cshtml
@model cwagnerShoppingApp.Models.CodeFirst.Item

@{
    ViewBag.Title = "Delete";
}

<div class="InnerContent">
    <h2>Delete Item</h2>

    <h3>Are you sure you want to delete this?</h3>
    <div>
        <hr />
        <div>
            <img class="img-responsive" src="@Url.Content(Model.MediaURL)" />
        </div>
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.CreationDate)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.CreationDate)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.UpdatedDate)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.UpdatedDate)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Price)
            </dt>

            <dd>
                <p>$@Html.DisplayFor(model => model.Price)</p>
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.MediaURL)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.MediaURL)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Description)
            </dt>

            <dd>
                @Html.Raw(Model.Description)
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</div>

Views/Items/Details.cshtml
@model cwagnerShoppingApp.Models.CodeFirst.Item

@{
    ViewBag.Title = "Details";
}

<div class="InnerContent">
    <h2>Details</h2>

    <div>
        <hr />
        <div>
            <img class="img-responsive" src="@Url.Content(Model.MediaURL)" />
        </div>
        <dl class="dl-horizontal">
            @*<dt>
                @Html.DisplayNameFor(model => model.CreationDate)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.CreationDate)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.UpdatedDate)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.UpdatedDate)
            </dd>*@

            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Price)
            </dt>

            <dd>
                <p>$@Html.DisplayFor(model => model.Price)</p>
            </dd>

            @*<dt>
                @Html.DisplayNameFor(model => model.MediaURL)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.MediaURL)
            </dd>*@

            <dt>
                @Html.DisplayNameFor(model => model.Description)
            </dt>

            <dd>
                @Html.Raw(Model.Description)
            </dd>

        </dl>
    </div>
    <div>
        @if (Request.IsAuthenticated)
        {
            using (Html.BeginForm("Create", "CartItems", new { itemId = Model.Id }, FormMethod.Post, null))
            {
                @Html.AntiForgeryToken();
                <p id="BuyNowButton"><input type="submit" class="btn btn-sm" value="Buy now!" /></p>
            }
        }
        @if (User.IsInRole("Admin"))
        {
            <p>
                @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
                @Html.ActionLink("Back to List", "Index")
            </p>
        }
        else
        {
            @Html.ActionLink("Back to List", "Index")
        }
    </div>
</div>

Views/Items/Edit.cshtml
@model cwagnerShoppingApp.Models.CodeFirst.Item

@{
    ViewBag.Title = "Edit";
}

<div class="InnerContent">
    <h2>Edit Item</h2>


    @using (Html.BeginForm("Edit", "Items", new { mediaURL = Model.MediaURL }, FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)
            @Html.HiddenFor(model => model.CreationDate)

            @*<div class="form-group">
                @Html.LabelFor(model => model.CreationDate, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CreationDate, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CreationDate, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.UpdatedDate, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.UpdatedDate, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.UpdatedDate, "", new { @class = "text-danger" })
                </div>
            </div>*@

            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">Upload Image</label>
                <div class="col-md-10">
                    <input name="image" type="file" class="form-control" />
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <textarea id="editor" class="form-control" name="Description" rows="5">@Model.Description</textarea>
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/tinymce/tinymce.min.js"></script>
    <script src="~/Scripts/tinymce/jquery.tinymce.min.js"></script>
    <script type="text/javascript">
        $(function () {
            tinymce.init({
                selector: '#editor'
            });
        }); </script>
}

Views/Items/Index.cshtml
@model IEnumerable<cwagnerShoppingApp.Models.CodeFirst.Item>

<!--Start of front page displayed watches-->
<!--large watch picture-->
<div class="row LgWatchPic">
    <div class="col-md-12">
        <div>
            <p><b>New arrivals</b></p>
            <a href="#Watches" class="btn btn-sm">Shop now</a>
        </div>
    </div>
</div>
<!--watches rows-->
<div class="CreateNew">
    @if (User.IsInRole("Admin"))
    {
        @Html.ActionLink("Create New", "Create");
    }
</div>
<div class="row WatchRow1" id="Watches">
    @foreach (var item in Model)
            {
        <div class="col-sm-3">
            <div>
                <a href="@Url.Action("Details", "Items",  new { id = item.Id })">
                    <p><b>@item.Name</b></p>
                    <img class="img-responsive" src="@Url.Content(item.MediaURL)" />
                </a>
                <p>$@item.Price</p>
                @if (Request.IsAuthenticated)
                {
                    using (Html.BeginForm("Create", "CartItems", new { itemId = item.Id }, FormMethod.Post, null))
                    {
                        @Html.AntiForgeryToken();
                        <p id="BuyNowButton"><input type="submit" class="btn btn-sm" value="Buy now!" /></p>
                    }
                }
                @if (User.IsInRole("Admin"))
                {
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) <span> | </span>;
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id });
                    <p><br /></p>;
                }
                <p><br /></p>
            </div>
        </div>
    }
</div>
<!--Start of Subscribe block-->
<div id="Subscribe" class="row SubscribeDiv">
    <div class="col-sm-12">
        <h1>Subscribe</h1>
        <p>To receive special offers and <span style="color:red">VIP</span> treatment:</p>
        @using (Html.BeginForm("Subscribe", "Contact"))
        {
            <input placeholder="Enter e-mail address" />
            <input type="submit" value="Subscribe" class="btn btn-default" />
        }
    </div>
</div>
<!--End of Subscribe block-->
<!--Start of Contact block-->
<div class="row ContactRow">
    <div class="col-xs-4 ContactUs">
        <h4><b>Contact Us</b></h4>
        <p>Questions?  Comments?</p>
        @using (Html.BeginForm("Index", "Contact"))
        {
            <input placeholder="Name" />
            <input placeholder="E-mail" />
            <input placeholder="Subject" />
            <input placeholder="Message" />
            <input type="submit" value="Send" class="btn btn-default" />
        }
    </div>
    <!--End of Contact block-->
    <!--Start of About column-->
    <div class="col-xs-4 AboutUs" style="text-align:center">
        <h4><b>About</b></h4>
        <a href="@Url.Action("About", "Home")">About us</a>
        @Html.ActionLink("Employment Opportunities", "Employment", "Contact")
        <a href="@Url.Action("Contact", "Home")">Support</a>
        <a href="https://goo.gl/maps/PYk2pCYTwZx" target="_blank">Find Us</a>
    </div>
    <!--End of About column-->
    <!--Start of Store info column-->
    <div class="col-xs-4" style="text-align:center">
        <div>
            <h4><b>Store</b></h4>
            <p><i class="fa fa-map-marker"> <a href="https://goo.gl/maps/PYk2pCYTwZx" target="_blank" style="color:black">Watches R Us</a></i></p>
            <p><i class="fa fa-phone"> (555) 555-5555</i></p>
            <p><i class="fa fa-envelope"> watches@email.com</i></p>
            <p><br /></p>
            <h4><b>We accept</b></h4>
            <p><i class="fa fa-cc-amex"> American Express</i></p>
            <p><i class="fa fa-cc-visa"> WRU Visa</i></p>
            <i class="fa fa-facebook"></i>
            <i class="fa fa-instagram"></i>
            <i class="fa fa-twitter"></i>
            <i class="fa fa-snapchat"></i>
            <i class="fa fa-pinterest"></i>
        </div>
    </div>
    <!--End of Store info column-->
</div>
<!--End of front page displayed watches-->

Views/Items/Index2.cshtml
@model IEnumerable<cwagnerShoppingApp.Models.CodeFirst.Item>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CreationDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UpdatedDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MediaURL)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.CreationDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UpdatedDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MediaURL)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

Views/Items/NightSeries.cshtml
@{
    ViewBag.Title = "NightSeries";
}

<div class="InnerContent">
    <h2>Night Series</h2>

    <div>
        <h3><b>COMING SOON!!!</b></h3>
        <h4>Please check back soon or subscribe for updates!</h4>
        <p>
            Browse watches from our newest collections!  Our Night Series includes some of the most mysterious and eye-catching watches.
            Stand out in the crowd with one of these beauties!
        </p>
    </div>
</div>